#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
    # Write your code here
    INTEGER_ARRAY = [];
    for i in range(len(grades)):
        temp = (grades[i] // 5)+1
        if(grades[i] < 38):
            INTEGER_ARRAY.append(grades[i])
        elif(temp * 5 - grades[i] < 3):
            INTEGER_ARRAY.append(temp * 5)
        else:
            INTEGER_ARRAY.append(grades[i])
    return INTEGER_ARRAY

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
